pipeline 
{
    agent any

    tools 
    {
        nodejs "nodejs"
    }

    stages
    {
        stage('Checkout') 
        {
            steps 
            {
                checkout scm
            }
        }

        stage('Build') 
        {
            steps 
            {
                // Install project dependencies
                sh 'npm install'

                // Fix vulnerabilities in project dependencies
                sh 'npm audit fix --force'

                // Verify Dockerfile exists
                sh 'ls -l'
                
                // Build the project
                sh 'npm run build'
            }
        }
    }
}
