pipeline {
    agent any
    stages {
        stage('OWASP Dependency-Check Vulnerabilities') {
            steps {
                script {
                    dependencyCheck additionalArguments: ''' 
                    -o './'
                    -s './'
                    -f 'ALL' 
                    --prettyPrint''', odcInstallation: 'OWASP Dependency-Check Vulnerabilities'
        
                    dependencyCheckPublisher pattern: 'dependency-check-report.xml'
                }
            }
        }
    }
    post {
        always {
            echo 'Cleaning up...'
        }
    }
}
